server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://identity-service:8080
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE,PATCH
                backoff:
                  interval: 1000
                  maxInterval: 5000
                  firstBackoff: 1000
        - id: profile_service
          uri: http://profile-service:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE,PATCH
                backoff:
                  interval: 1000
                  maxInterval: 5000
                  firstBackoff: 1000
        - id: notification-service
          uri: http://notification-service:8082
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE,PATCH
                backoff:
                  interval: 1000
                  maxInterval: 5000
                  firstBackoff: 1000
        - id: schedule-service
          uri: http://schedule-service:8083
          predicates:
            - Path=${app.api-prefix}/schedules/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE,PATCH
                backoff:
                  interval: 1000
                  maxInterval: 5000
                  firstBackoff: 1000
        - id: order-service
          uri: http://order-service:8084
          predicates:
            - Path=${app.api-prefix}/orders/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE,PATCH
                backoff:
                  interval: 1000
                  maxInterval: 5000
                  firstBackoff: 1000
        - id: note-service
          uri: http://note-service:8085
          predicates:
            - Path=${app.api-prefix}/notes/**
          filters:
            - StripPrefix=2
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,DELETE,PATCH
                backoff:
                  interval: 1000
                  maxInterval: 5000
                  firstBackoff: 1000
      cors:
        allowedOrigins:
          - "http://localhost:8888"
          - "http://localhost:3000"
        allowedMethods: "*"
        allowedHeaders: "*"
        allowCredentials: true

springdoc:
  api-docs:
    enabled: true
    path: ${app.api-prefix}/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: "/api/v1/identity/v3/api-docs"
        name: "Identity Service"
      - url: "${app.api-prefix}/profile/users/v3/api-docs"
        name: "Profile Service"
      - url: "${app.api-prefix}/notification/v3/api-docs"
        name: "Notification Service"
      - url: "${app.api-prefix}/schedules/v3/api-docs"
        name: "Schedule Service"
      - url: "${app.api-prefix}/orders/v3/api-docs"
        name: "Order Service"
      - url: "${app.api-prefix}/notes/v3/api-docs"
        name: "Note Service"
    csrf:
      enabled: true